### ISSUE TITLE
Adaptivité du Jeu (Canvas)

### ISSUE THREAD

**Issue by LenyMarco** [NarvinChana/ProjetISN#2]
Problème adaption de la taille du canvas en fonction de la taille de l'écran de l'utilisateur.

**Comment by NarvinChana** [comment]
Solution : 
Mettre un format standard (90% des utilisateurs ont un format d'au moins 800x400px

Article qui dit parle de comment faire un jeu qui s'adapte à la résolution de l'utilisateur : https://www.html5rocks.com/en/tutorials/casestudies/gopherwoord-studios-resizing-html5-games/

**Comment by NarvinChana** [comment]
Un Pull Request a été ajouté.

**Comment by LenyMarco** [comment]
solved
